/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSEvent */

#ifndef _Included_com_southernstars_sscore_JSSEvent
#define _Included_com_southernstars_sscore_JSSEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef com_southernstars_sscore_JSSEvent_kRise
#define com_southernstars_sscore_JSSEvent_kRise -1L
#undef com_southernstars_sscore_JSSEvent_kTransit
#define com_southernstars_sscore_JSSEvent_kTransit 0L
#undef com_southernstars_sscore_JSSEvent_kSet
#define com_southernstars_sscore_JSSEvent_kSet 1L
#undef com_southernstars_sscore_JSSEvent_kNewMoon
#define com_southernstars_sscore_JSSEvent_kNewMoon 0.0
/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    semiDiurnalArc
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSEvent_semiDiurnalArc
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    riseTransitSet
 * Signature: (Lcom/southernstars/sscore/JSSTime;DDIDDD)Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSEvent_riseTransitSet__Lcom_southernstars_sscore_JSSTime_2DDIDDD
  (JNIEnv *, jclass, jobject, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    riseTransitSet
 * Signature: (Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;ID)Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSEvent_riseTransitSet__Lcom_southernstars_sscore_JSSTime_2Lcom_southernstars_sscore_JSSCoordinates_2Lcom_southernstars_sscore_JSSObject_2ID
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    riseTransitSetSearch
 * Signature: (Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;ID)Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSEvent_riseTransitSetSearch
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    riseTransitSetSearchDay
 * Signature: (Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;ID)Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSEvent_riseTransitSetSearchDay
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    riseTransitSet
 * Signature: (Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;D)Lcom/southernstars/sscore/JSSPass;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSEvent_riseTransitSet__Lcom_southernstars_sscore_JSSTime_2Lcom_southernstars_sscore_JSSCoordinates_2Lcom_southernstars_sscore_JSSObject_2D
  (JNIEnv *, jclass, jobject, jobject, jobject, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    findSatellitePaJsses
 * Signature: (Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSTime;DLjava/util/ArrayList;I)I
 */
JNIEXPORT jint JNICALL Java_com_southernstars_sscore_JSSEvent_findSatellitePaJsses
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jdouble, jobject, jint);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    nextMoonPhase
 * Signature: (Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSObject;D)Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSEvent_nextMoonPhase
  (JNIEnv *, jclass, jobject, jobject, jobject, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    findConjunctions
 * Signature: (Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSTime;Ljava/util/ArrayList;I)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSEvent_findConjunctions
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    findOppositions
 * Signature: (Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSTime;Ljava/util/ArrayList;I)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSEvent_findOppositions
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    findNearestDistances
 * Signature: (Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSTime;Ljava/util/ArrayList;I)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSEvent_findNearestDistances
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_southernstars_sscore_JSSEvent
 * Method:    findFarthestDistances
 * Signature: (Lcom/southernstars/sscore/JSSCoordinates;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSObject;Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSTime;Ljava/util/ArrayList;I)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSEvent_findFarthestDistances
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
