/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSSpherical */

#ifndef _Included_com_southernstars_sscore_JSSSpherical
#define _Included_com_southernstars_sscore_JSSSpherical
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSSpherical
 * Method:    fromVector
 * Signature: (Lcom/southernstars/sscore/JSSVector;)Lcom/southernstars/sscore/JSSSpherical;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSSpherical_fromVector
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_southernstars_sscore_JSSSpherical
 * Method:    toVector
 * Signature: ()Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSSpherical_toVector
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSSpherical
 * Method:    toVectorVelocity
 * Signature: (Lcom/southernstars/sscore/JSSSpherical;)Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSSpherical_toVectorVelocity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSSpherical
 * Method:    angularSeparation
 * Signature: (Lcom/southernstars/sscore/JSSSpherical;)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSSpherical_angularSeparation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSSpherical
 * Method:    positionAngle
 * Signature: (Lcom/southernstars/sscore/JSSSpherical;)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSSpherical_positionAngle
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
