/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSJPLDEphemeris */

#ifndef _Included_com_southernstars_sscore_JSSJPLDEphemeris
#define _Included_com_southernstars_sscore_JSSJPLDEphemeris
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_isOpen
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_close
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    getConstantNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_getConstantNumber
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    getConstantName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_getConstantName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    getConstantValue
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_getConstantValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    getStartJED
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_getStartJED
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    getStopJED
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_getStopJED
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    getStep
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_getStep
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSJPLDEphemeris
 * Method:    compute
 * Signature: (IDZLcom/southernstars/sscore/JSSVector;Lcom/southernstars/sscore/JSSVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_southernstars_sscore_JSSJPLDEphemeris_compute
  (JNIEnv *, jclass, jint, jdouble, jboolean, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
