/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSHourMinSec */

#ifndef _Included_com_southernstars_sscore_JSSHourMinSec
#define _Included_com_southernstars_sscore_JSSHourMinSec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSHourMinSec
 * Method:    fromString
 * Signature: (Ljava/lang/String;)Lcom/southernstars/sscore/JSSHourMinSec;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSHourMinSec_fromString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_southernstars_sscore_JSSHourMinSec
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_southernstars_sscore_JSSHourMinSec_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
