/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSVector */

#ifndef _Included_com_southernstars_sscore_JSSVector
#define _Included_com_southernstars_sscore_JSSVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSVector
 * Method:    fromSpherical
 * Signature: (Lcom/southernstars/sscore/JSSSpherical;)Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSVector_fromSpherical
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_southernstars_sscore_JSSVector
 * Method:    toSpherical
 * Signature: ()Lcom/southernstars/sscore/JSSSpherical;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSVector_toSpherical
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSVector
 * Method:    toSphericalVelocity
 * Signature: (Lcom/southernstars/sscore/JSSVector;)Lcom/southernstars/sscore/JSSSpherical;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSVector_toSphericalVelocity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSVector
 * Method:    angularSeparation
 * Signature: (Lcom/southernstars/sscore/JSSVector;)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSVector_angularSeparation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSVector
 * Method:    positionAngle
 * Signature: (Lcom/southernstars/sscore/JSSVector;)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSVector_positionAngle
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
