/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSCoordinates */

#ifndef _Included_com_southernstars_sscore_JSSCoordinates
#define _Included_com_southernstars_sscore_JSSCoordinates
#ifdef __cplusplus
extern "C" {
#endif
#undef com_southernstars_sscore_JSSCoordinates_kFundamental
#define com_southernstars_sscore_JSSCoordinates_kFundamental 0L
#undef com_southernstars_sscore_JSSCoordinates_kEquatorial
#define com_southernstars_sscore_JSSCoordinates_kEquatorial 1L
#undef com_southernstars_sscore_JSSCoordinates_kEcliptic
#define com_southernstars_sscore_JSSCoordinates_kEcliptic 2L
#undef com_southernstars_sscore_JSSCoordinates_kGalactic
#define com_southernstars_sscore_JSSCoordinates_kGalactic 3L
#undef com_southernstars_sscore_JSSCoordinates_kHorizon
#define com_southernstars_sscore_JSSCoordinates_kHorizon 4L
#undef com_southernstars_sscore_JSSCoordinates_kKmPerAU
#define com_southernstars_sscore_JSSCoordinates_kKmPerAU 1.495978707E8
#undef com_southernstars_sscore_JSSCoordinates_kKmPerEarthRadii
#define com_southernstars_sscore_JSSCoordinates_kKmPerEarthRadii 6378.137
#undef com_southernstars_sscore_JSSCoordinates_kEarthFlattening
#define com_southernstars_sscore_JSSCoordinates_kEarthFlattening 0.0033528131778969143
#undef com_southernstars_sscore_JSSCoordinates_kLightKmPerSec
#define com_southernstars_sscore_JSSCoordinates_kLightKmPerSec 299792.458
#undef com_southernstars_sscore_JSSCoordinates_kLightAUPerDay
#define com_southernstars_sscore_JSSCoordinates_kLightAUPerDay 173.1446326742403
#undef com_southernstars_sscore_JSSCoordinates_kAUPerLY
#define com_southernstars_sscore_JSSCoordinates_kAUPerLY 63241.077084266275
#undef com_southernstars_sscore_JSSCoordinates_kLYPerAU
#define com_southernstars_sscore_JSSCoordinates_kLYPerAU 1.581250740982066E-5
/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    create
 * Signature: (Lcom/southernstars/sscore/JSSTime;Lcom/southernstars/sscore/JSSSpherical;)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSCoordinates_create
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSCoordinates_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    setTime
 * Signature: (Lcom/southernstars/sscore/JSSTime;)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSCoordinates_setTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    setLocation
 * Signature: (Lcom/southernstars/sscore/JSSSpherical;)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSCoordinates_setLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getTime
 * Signature: ()Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getTime
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getLocation
 * Signature: ()Lcom/southernstars/sscore/JSSSpherical;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getJED
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_getJED
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getLST
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_getLST
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getObliquity
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_getObliquity
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getNutationConstants
 * Signature: (DLjava/lang/Double;Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSCoordinates_getNutationConstants
  (JNIEnv *, jclass, jdouble, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getPrecessionConstants
 * Signature: (DLjava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_com_southernstars_sscore_JSSCoordinates_getPrecessionConstants
  (JNIEnv *, jclass, jdouble, jobject, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getPrecessionMatrix
 * Signature: (D)Lcom/southernstars/sscore/JSSMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getPrecessionMatrix
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getNutationMatrix
 * Signature: (DDD)Lcom/southernstars/sscore/JSSMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getNutationMatrix
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getEclipticMatrix
 * Signature: (D)Lcom/southernstars/sscore/JSSMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getEclipticMatrix
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getHorizonMatrix
 * Signature: (DD)Lcom/southernstars/sscore/JSSMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getHorizonMatrix
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    getGalacticMatrix
 * Signature: ()Lcom/southernstars/sscore/JSSMatrix;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_getGalacticMatrix
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    transform
 * Signature: (IILcom/southernstars/sscore/JSSVector;)Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_transform__IILcom_southernstars_sscore_JSSVector_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    transform
 * Signature: (IILcom/southernstars/sscore/JSSSpherical;)Lcom/southernstars/sscore/JSSSpherical;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_transform__IILcom_southernstars_sscore_JSSSpherical_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    applyAberration
 * Signature: (Lcom/southernstars/sscore/JSSVector;)Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_applyAberration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    removeAberration
 * Signature: (Lcom/southernstars/sscore/JSSVector;)Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_removeAberration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    redShiftToRadVel
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_redShiftToRadVel
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    radVelToRedShift
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_radVelToRedShift
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    toGeocentric
 * Signature: (Lcom/southernstars/sscore/JSSSpherical;DD)Lcom/southernstars/sscore/JSSVector;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_toGeocentric
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    toGeodetic
 * Signature: (Lcom/southernstars/sscore/JSSVector;DD)Lcom/southernstars/sscore/JSSSpherical;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSCoordinates_toGeodetic
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    refractionAngle
 * Signature: (DZ)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_refractionAngle
  (JNIEnv *, jclass, jdouble, jboolean);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    applyRefraction
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_applyRefraction
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_southernstars_sscore_JSSCoordinates
 * Method:    removeRefraction
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSCoordinates_removeRefraction
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
