/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSCalendar */

#ifndef _Included_com_southernstars_sscore_JSSCalendar
#define _Included_com_southernstars_sscore_JSSCalendar
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
