/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSDate */

#ifndef _Included_com_southernstars_sscore_JSSDate
#define _Included_com_southernstars_sscore_JSSDate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSDate
 * Method:    fromJulianDate
 * Signature: (Lcom/southernstars/sscore/JSSTime;I)Lcom/southernstars/sscore/JSSDate;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSDate_fromJulianDate
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_southernstars_sscore_JSSDate
 * Method:    toJulianDate
 * Signature: ()Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSDate_toJulianDate
  (JNIEnv *, jobject);

/*
 * Class:     com_southernstars_sscore_JSSDate
 * Method:    format
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_southernstars_sscore_JSSDate_format
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
