/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSTime */

#ifndef _Included_com_southernstars_sscore_JSSTime
#define _Included_com_southernstars_sscore_JSSTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSTime
 * Method:    fromSystem
 * Signature: ()Lcom/southernstars/sscore/JSSTime;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSTime_fromSystem
  (JNIEnv *, jclass);

/*
 * Class:     com_southernstars_sscore_JSSTime
 * Method:    getJulianEphemerisDate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_southernstars_sscore_JSSTime_getJulianEphemerisDate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
