/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_southernstars_sscore_JSSDegMinSec */

#ifndef _Included_com_southernstars_sscore_JSSDegMinSec
#define _Included_com_southernstars_sscore_JSSDegMinSec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_southernstars_sscore_JSSDegMinSec
 * Method:    fromString
 * Signature: (Ljava/lang/String;)Lcom/southernstars/sscore/JSSDegMinSec;
 */
JNIEXPORT jobject JNICALL Java_com_southernstars_sscore_JSSDegMinSec_fromString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_southernstars_sscore_JSSDegMinSec
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_southernstars_sscore_JSSDegMinSec_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
